on: push
name: Git Creation Demo
jobs:
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git Creation Demo
        uses: senzing/git-action-git-issue-creation@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_OWNER: 'Senzing'
          GITHUB_REPOSITORY: git-action-github-issue-creation
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'